### ISSUE TITLE
请问有一起合作翻译的意向吗？

### ISSUE THREAD

**Issue by yiluomyt** [qihuanlu01/aspcore-2.0--#1]
你好，我是B站上[ASP.NET Core 2.0初级教程](https://www.bilibili.com/video/av29767316)的翻译，最近发现你也在翻译这个系列，不知你是否有意向一起合作把这个系列的翻译做得更好？
我们是B站[Microsoft资讯](https://space.bilibili.com/134452343/#/)(非官方)下的一个翻译小组，也都是.NET Core的爱好者，目前已经完成的有该系列的初级教程，正在翻译中级教程，这是我们在GitHub上的[账号](https://github.com/mstechanli)。
以下是我们在B站上的视频链接:
- 初版 https://www.bilibili.com/video/av29767316
- 正式版 https://www.bilibili.com/video/av27946437

如果您有想法的话，请联系我(*^_^*)

邮箱: mytyiluo@outlook.com
QQ: 715147130

**Comment by qihuanlu01** [comment]
啊偶，你咋找到我的邮件地址的？可以一起翻译，不过现在已经都已经是dotnet core 2.1了，你们现在翻译到哪里了

在 2018-09-20 12:16:42，"毛寅滔" <notifications@github.com> 写道：


你好，我是B站上ASP.NET Core 2.0初级教程的翻译，最近发现你也在翻译这个系列，不知你是否有意向一起合作把这个系列的翻译做得更好？
我们是B站Microsoft资讯(非官方)下的一个翻译小组，也都是.NET Core的爱好者，目前已经完成的有该系列的初级教程，正在翻译中级教程，这是我们在GitHub上的账号。
以下是我们在B站上的视频链接:

初版 https://www.bilibili.com/video/av29767316
正式版 https://www.bilibili.com/video/av27946437

如果您有想法的话，请联系我(^_^)

邮箱: mytyiluo@outlook.com
QQ: 715147130

**Comment by yiluomyt** [comment]
我在你的repo下提交了一个Issue，邮件是GitHub的自动提醒，我这是看不到你邮箱的(。・∀・)ノ

这是我们目前在用的组织账号，相关repo都在这，https://github.com/MSTechAnLi

关于ASP.NET Core 2.1的话，我目前也在用，但基础部分改动不大，我觉得2.0的视频还是值得翻一下的。
进度的话，我目前主要还是在做初级教程的校对工作，因为字幕组这边对格式上有一些要求。此外的话，我同伴刚刚开始翻中级教程的第一节。

如果觉得可以的话，不妨加个QQ吧，交流会方便一些。(*^_^*)
